config/routes.rb
Rails.application.routes.draw do

  resources :todos, only: %i[create edit update]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  after_commit :publish_todo, on: :create
  after_commit :publish_update_todo, on: :update

  def publish_todo
    broadcast_append_to 'todos_stream', target: 'todos_list', partial: 'todos/item', locals: { todo: self }
  end

  def publish_update_todo
    broadcast_replace_to 'todos_stream', target: "todo_#{id}", partial: 'todos/item', locals: { todo: self }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @todos = Todo.all
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def edit
    @todo = Todo.find(params[:id])
    Turbo::StreamsChannel.broadcast_replace_to 'todos_stream', target: "todo_status_#{@todo.id}", partial: 'todos/status'
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
  end

  def create
    @todo = Todo.create(todo_params)
    @todos = Todo.all
    # respond_to do |format|
    #   format.turbo_stream
    # end
  end

  private

  def todo_params
    params.require(:todo).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/index.html.erb
<div>
  <%= turbo_stream_from 'todos_stream' %>
  <h1 class="font-bold text-4xl">ToDo List</h1>
  <%= render partial: 'todos/form', locals: { todo: Todo.new, frame_id: 'new_todo' } %>
  <%= turbo_frame_tag 'todos_list' do %>
    <%= render 'todos/list', todos: @todos %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboHotwireTraining</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/todos/_form.html.erb
<%= turbo_frame_tag frame_id do %>
  <%= form_with model: todo do |form| %>
    <%= form.text_field :name %>
    <%= form.submit todo.id ? :update : :add, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
  <% end %>
<% end %>

app/views/todos/_item.html.erb
<%= turbo_frame_tag "todo_#{todo.id}" do %>
  <p><%= link_to todo.name, edit_todo_path(todo.id) %></p>
  <%= turbo_frame_tag "todo_status_#{todo.id}" do %>

  <% end %>
<% end %>

app/views/todos/_list.html.erb
<% todos.each do |todo| %>
  <%= render partial: 'todos/item', locals: { todo: todo } %>
<% end %>

app/views/todos/_status.html.erb
Updating...

app/views/todos/create.turbo_stream.erb
<%#= turbo_frame_tag 'new_todo' do %>
<%#= render 'todos/form' %>
<%# end %>
<%= turbo_stream.replace 'new_todo', partial: 'todos/form', locals: { todo: Todo.new, frame_id: 'new_todo' } %>

app/views/todos/edit.html.erb
<%= render partial: 'todos/form', locals: { todo: @todo, frame_id: "todo_#{@todo.id}" } %>